#!/usr/bin/env bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# clean up output test files
rm "$DIR"/../test_ciphertext*.txt
rm "$DIR"/../test_plaintext*.txt

# CMAKE_INSTALL_PREFIX="$DIR/.." make release

# export the key
export AES_CLI_KEY=$(cat "$DIR/../test_key.txt")

# encrypt a file
"$DIR"/aes-cli encrypt -i "$DIR"/../plaintext.txt -o "$DIR"/../test_ciphertext_GCM.txt -m GCM
"$DIR"/aes-cli decrypt -i "$DIR"/../test_ciphertext_GCM.txt -o "$DIR"/../test_plaintext_GCM.txt -m GCM

"$DIR"/aes-cli encrypt -i "$DIR"/../plaintext.txt -o "$DIR"/../test_ciphertext_CBC.txt -m CBC
"$DIR"/aes-cli decrypt -i "$DIR"/../test_ciphertext_CBC.txt -o "$DIR"/../test_plaintext_CBC.txt -m CBC

"$DIR"/aes-cli encrypt -i "$DIR"/../plaintext.txt -o "$DIR"/../test_ciphertext_ECB.txt -m ECB
"$DIR"/aes-cli decrypt -i "$DIR"/../test_ciphertext_ECB.txt -o "$DIR"/../test_plaintext_ECB.txt -m ECB
